- README.md
I did some very quick proofreading of the README and made a few small changes. Then I used VSCode's tools (formatter) to fix some common Markdown mistakes. There are probably still some mistakes I didn't catch as I didn't read everything yet.
Should we remove the section about MMU_UNLOCK now that you don't actually need to run that on every failure?
> Very quick proofread and making the Markdown compliant/valid

- extras/mmu.py
**Issue:**
There are two main things this PR addresses: 
1. When manually setting a servo angle via `MMU_SERVO ANGLE=<something>`, the internal angle state is not updated. This means that if the next servo command would bring it to its old state, no movement would be issued since it doesn't think it ever left that position. Simple repro case (may have to adjust values for your setup):
```
MMU_SERVO POS=move ; moves
MMU_SERVO ANGLE=50 ; moves
MMU_SERVO POS=move ; does not move
```
2. When turning off the motors, the servo will not move if it thinks it's in the correct state. This would normally be fine, but I've run into issues where the servo gets bound up on something and it would help if it tried to get back into its safe position when the other motors get turned off.
**Fix …
> Reset servo state when manually setting angles/turning motors off

- README.md
- doc/command_ref.md
- extras/mmu.py
**Issue:**
When calling `MMU_SYNC_GEAR_MOTOR` during a print, the gear current is set to 100%
**Fix Description:**
`cmd_MMU_SYNC_GEAR_MOTOR` and accompanying docs have been updated to allow manually specifying whether it should treat `_sync_gear_to_extruder` like you're in a print. The default is automatically determined based on current print state
**GitHub Issues Resolved:**
None
> Update MMU_SYNC_GEAR_MOTOR to allow specifying print state

- extras/mmu.py
Replicate V3 behavior: unlock before loading/unloading extruder if the print is currently paused
Fixes #13
> Fix lockup if target temperature is reset during pause

- config/base/mmu_parameters.cfg
- doc/configuration.md
- extras/mmu.py
**Issues:**
- `_ensure_safe_extruder_temperature` would set the wrong temperature coming out of a pause if `min_temp_extruder` is greater than the current printing temperature
- In certain conditions, `MMU_STEP_SET_FILAMENT` would fail due to referencing an undefined variable
**Fix Description:**
- `_ensure_safe_extruder_temperature` now uses Klipper's `min_extrude_temp` as the baseline for safety
- `min_temp_extruder` has been renamed and repurposed to `default_extruder_temp`. This now represents a sensible baseline for actions out-of-print as well as a workable fallback if the target temperature somehow gets set to an unsafe value during Happy Hare operations
-  The typo in `MMU_STEP_SET_FILAMENT` has been resolved
**Bonus Nachos:**
- A new helper, `_wrap_action`, has been introduced to …
> Temp logic updates and misc bugfixes

- extras/mmu.py
Should resolve Issue #37 .  Please see the comments in that issue for a long winding report, triage, and thought process.
The short version is that _handle_runout() should set self.paused_extruder_temp so that when the runout code eventually calls cmd_MMU_RESUME(), the extruder temperature isn't changed to self.default_extruder_temp (which might be safe for tips, but not for printing.)
> store the extruder temperature in _handle_runout

- extras/mmu.py
_home_selector() allows a max movement of "_get_max_movement(-1)" for homing.  _get_max_movement() was only compensating for the bypass offset if the parameter was -2 (TOOL_GATE_BYPASS)
This PR will allow a max movement that does consider the bypass offset (for ERCF v2+) if the target gate is anything less than 0, which includes UNKNOWN (used by _home_selector) as well as BYPASS.  
The change purposely assumes any other negative "gate" value would indicate some type of unknown or undefined gate which would allow movement to/from the bypass.
Fixes https://github.com/moggieuk/Happy-Hare/issues/27
> fix _get_max_movement() on ERCF v2 for homing

- extras/mmu.py
Fix for issue #36
target_temp_override is passed in as 0 from self.paused_extruder_temp (separate issue), evaluating to the first if statement and causing new_target_temp to be assigned 0.
This ultimately leads to the new extruder temp being set to the MMU's default temp. I don't see a reason in any scenario where checking if target_temp_override >= klipper_minimum_temp could cause issues, as we shouldn't be printing below that temp anyway.
Tested in my setup (RPi4, RatOS, RatRig 3.1 300mm) and fixed my issue.
> check that target_temp_override is >=  klipper_minimum_temp

- extras/mmu.py
Fix for issue #36 - When a manual pause is issued, we don't currently intercept the macro, and so do not set self.paused_extruder_temp - this causes the target_temp to be set to the default extruder temp when RESUME is called and intercepted by Happy Hare.
This ensures that no matter how the PAUSE macro is called, self.paused_extruder_temp will be set.
> Confirm self.paused_extruder_temp is set on cmd_MMU_RESUME

- config/base/mmu_software.cfg
- extras/mmu.py
Allows tip forming macro to set a custom value of park_pos. This is useful for tip forming routines like filament cutters, where the park pos should be managed by the cut macro.
> allow custom value of park_pos in tip_forming macro

- config/base/mmu_parameters.cfg
- extras/mmu.py
In my mission to make loading/unloading more reliable for my setup (see also #74), I realized that if both a gate endstop and encoder is defined, there seems to be an implicit assumption in the code that once the filament has reached the gate endstop, that it will engage with the encoder. 
This is usually not the case and I figured it would be helpful to make the distance between the encoder and gate endstop customizable.  This hopefully removes the error during for example bowden length calibration where the initial loading distance before the filament reaches the encoder seems to (wrongly) count towards the "slippage" of the filament.
This change is by no means complete; I might have missed places in the code and docs that need updating.  Feel free to leave comments and I will try to …
> Add support for specifying the distance between the gate endstop and encoder

- extras/mmu.py
When homing to an extruder endstop, we don't expect any springback to happen, since the filament is just hanging out happily in its PTFE tube
> Fix springback calculations when using an extruder endstop

- extras/mmu.py
Ran into this as I'm doing test prints and trying to tweak some things.  If this log line is encountered as-is, klipper will crash with the following stack trace:
```
Traceback (most recent call last):
File "/home/pi/klipper/klippy/gcode.py", line 211, in _process_commands
handler(gcmd)
File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 189, in cmd
self.template.run_gcode_from_command(kwparams)
File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
self.gcode.run_script_from_command(self.render(context))
File "/home/pi/klipper/klippy/gcode.py", line 226, in run_script_from_command
self._process_commands(script.split('\n'), need_ack=False)
File "/home/pi/klipper/klippy/gcode.py", line 211, in _process_commands
handler(gcmd)
File …
```
> Fix string formatting in log

- config/base/mmu_parameters.cfg
- extras/mmu.py
- extras/mmu_sensors.py
Attempts to address MMU gate endstop naming inconsistencies by using shared variables/constants to hold the endstop names.
Fixes #114.
> MMU gate endstop fixes

- extras/mmu_toolhead.py
[this commit](https://github.com/Klipper3d/klipper/commit/6cc409f6fb9f62226c56adcf80be32a0d2601ab1) breaks Happy Hare. This pull request fixes it.
> Rename MoveQueue to LookAheadQueue  to fix compatibility with latest Klipper

- config/base/mmu_cut_tip.cfg
> Fixes issue #184 - Filametrix cut with restore position tries to return to 0,0 usually destroying pin located near there.

- extras/mmu.py
Simple typo fix. Was having issues using the `MMU_TEST_CONFIG` command to update these two runtime values. Aaaand... then I found out why :D
> Fix typo preventing sync multipliers from updating

- install.sh
Add new ``-r`` install.sh arg to allow ``printer.cfg`` and ``klipper.service`` references to be overridden when installing HH onto Repetier-Server.  
Repetier-Server supports multiple klipper instances and generates unique names for ``klipper.service`` and ``printer.cfg`` using a stub/instance reference. This allows users to specify the "stub" used to set this correctly.
For example - use ``-r LK5_Pro_ERCF`` to set klipper.service to ``klipper_LK5_Pro_ERCF.service`` & printer.cfg to ``LK5_Pro_ERCF.cfg``
``./install.sh -k /opt/klipper/LK5_Pro_ERCF -c /var/lib/Repetier-Server/database/klipper -m /opt/klipper/LK5_Pro_ERCF/moonraker -r LK5_Pro_ERCF -i``
Usage: ./install.sh [-k <klipper_home_dir>] [-c <klipper_config_dir>] [-m <moonraker_home_dir>] [-b <branch>] [-r \<Repetier-Server stub\>] …
> Add support for Repetier-Server install overrides

- README.md
- install.sh
There was a request from an user on Discord to be able to specify an alternative service name for klipper only:
https://discord.com/channels/460117602945990666/909743915475816458/1216405832456212652
While this is somewhat accomplished with the `-r` flag, this depends on the Repetier-Server. 
This added functionality allows setting the `${KLIPPER_SERVICE}` variable to a specific name. This would commonly be used if a user installed multiple klipper services with the commonly used `kiauh` utility.
> Add ability to specify alternative service name from kiauh install

- doc/configuration.md
Refined values for the G2E/Filametrix toolhead distances.
Added `variable_retract_length` and `variable_pushback_length` for tip cutting to both tables and added the relevant values for G2E and Rapido.
Added CAD measurements for Revo and estimated retract and pushback measurements (based on Rapido differences).
> Updated G2E/Filametrix files for cut tip

- install.sh
`egrep` and `fgrep` aliases have been deprecated for over 15 years, and for almost 2 years they are raising warnings (including on Arch Linux, which I'm running this software on): https://www.phoronix.com/news/GNU-Grep-3.8-Stop-egrep-fgrep
> replace egrep calls with grep -E

- extras/mmu.py
- extras/mmu_encoder.py
- extras/mmu_sensors.py
Basically fixes https://github.com/moggieuk/Happy-Hare/issues/246, in essence `pause_resume.pause` was triggered in sensors or encoder, but there was no resume. 
Also removed `_M400` call and replaced with direct `_movequeues_wait_moves`, otherwise it could be called after resume, which is not okay I guess :)
> Fix endless spool resume

- extras/mmu.py
To keep all funcitonality creating an exception in the check seemed cleaner.
> Fixes moggieuk/Happy-Hare/issues/#322

- extras/mmu.py
My Voron is using a long bowden cable, which is also extra wide as 2mm resulted in high friction loads and unloads.
The result is that after a tool swap, the filament was pushed into the extruder head and is slack, resulting in the clog detection triggering right after.
This is not a complete pull request as the amount of rollback and torque should probably be adjustable from the configuration files. Also, I still have trouble getting reliable swaps, with or without this change - so either I am missing something or I need to configure my printer better.
Anyway, comments welcome.
**What does this do?**
At each tool load, the filament is pushed down the tube, picked up by the extruder and then put into the parking position inside the extruder (both the ERCF feeder motor and extruder motor …
> Automatic pull-back of filament after loading long bowden cables

- config/base/mmu_software.cfg
Related to #272. MMU shouldn't try to load initial tool in case of using bypass.
> Fix load initial tool in case of using bypass

- components/mmu_server.py
- extras/mmu.py
Add the possibility to include only mmu_server into moonraker in order to expose spoolman methods for storing, setting, retrieving spools for printers.
- add the standalone operation to mmu_server
- switch to query object for mmu_server initialization to avoid passing arguments 
- minor fixes :
- gate assignment overflow check fixed
- minor linting issues
- Active spool setting has to be done manually
- is is possible no mmu module is present in klipper but mmu_server is enabled ?
- if klipper is down, mmu_server will default to nb_gates = 1 (standalone mode)
Below is a simple example cfg file to interface with this ecosystem 
```yml
[gcode_macro SET_ACTIVE_SPOOL]
description: Sets active spool to spool with given id.
Usage: SET_ACTIVE_SPOOL [ID=<int>]
gcode:
{% if params.ID %}
{% set id …
```
> Mmu server standalone

- config/addons/mmu_erec_cutter.cfg
Updated variable_feed_length for EREC cutter to work with V2 out of the box, which is based on the gate_parking_distance from mmu_parameter.cfg and adjusted the comment to show the values for ERCF V1.1 and V2+ others. This is based on the install.sh gate_parking_distance of 13 (ERCF V2 + others) vs 23(ERCF V1.1).
If not adjusted properly the cut length is not correct. Initial Macro came from me with these Values, since i still had gate_parking_distance of 23 left when upgrading from V1.1 to V2.
> Updated variable_feed_length for EREC Cutter for ERCF V2

- extras/mmu.py
Fixes `PAUSE` being called twice and out of order.
First `PAUSE` was called before `_save_toolhead_position_and_lift`, so the toolhead would not move to the correct position on resume.
> Fix PAUSE called twice

- components/mmu_server.py
I'm using OrcaSlicer and have the Verbose G-code option turned on. That causes T* commands to be emitted with a comment, and Happy Hare's G-code preprocessor no longer recognizes them. This is a simple regex fix to allow (and ignore) comments.
> Allow comments on toolchange commands to accommodate verbose slicer mode

- config/addons/blobifier.cfg
When using skew correction, a Blobifier shake operation can trigger an ‘out of range’ error.  This fix allows the user to apply a skew correction to both x and y axes.
cc: @Dendrowen 
Thank you for your consideration.
> Fix ‘out of range’ with Blobifier shake

- extras/mmu_toolhead.py
- install.sh
The Creality K1 series of 3d-printers runs on a MIPS CPU, under a heavily trimmed Linux system akin to that on WiFi routers. The current install script will not run on them.
Furthermore, on those printers, there are no users other than root present, the directories for klipper are always different from what you expect on a Pi-based system, the services run as init scripts (with no systemd present).
This PR suggests changes necessary for checking if the srcipt runs on such a system and adjusting the folders accordingly. It addresses the question in #311 and is similar to the script provided in that answer.
Closes #311, closes #189, closes #381
> Changes for Creality K1 series

- config/addons/blobifier.cfg
The associated IF/ELIF block was commented because BLOBIFIER_PARK's usage in INIT is broken in 2.7.1. 
Comment out the rest of the block to avoid a config read error.
> Patch _BLOBIFIER_INIT to comment out note for park

- extras/mmu.py
I noticed that `mmu_calibrate_bowden` wasn't working. It was loading filament up to the extruder gears, but then backing it away at most 135 mm. Since my bowden tube is ~700mm, this raises an error.
The use of `_unload_bowden` in `_calibrate_bowden_length_auto` was incorrect causing `self._unload_bowden(reference)` to do nothing, followed by `self._unload_gate()` trying to back the filament out (but expecting to go at most 135mm). Adding a `False` as a positional argument fixes this.
> Fix _unload_bowden arguments in _calibrate_bowden_length_auto

- extras/mmu.py
Just a simple fix to ensure the servo is down when starting MMU_TEST_TRACKING
Fixes issue #238
> Set servo to down during MMU_TEST_TRACKING

- extras/mmu.py
Certain unicode characters wouldn't match properly, e.g. the ™ in  "PolyLite™ ABS Black" (this is how it's defined in [SpoolmanDB](https://donkie.github.io/SpoolmanDB/)) would fail to be auto-mapped. I suspect that the methods to transfer it from spoolman or the slicer use slightly different unicode paths.
Also, although the documentation in `mmu_macro_vars.cfg` states it would match case-insensitive, it didn't. So I fixed that too. (The wiki doesn't mention it though)
```
```
I'm far from proficient with python, so possibly there's a better way? Basically I copied the implementation from here: https://docs.python.org/3/howto/unicode.html#comparing-strings
> Fix unicode filament names not matching with automap

- extras/mmu_machine.py
When configuring a stepper, it technically is not required to configure some things such as gear_ratio when you have a rotation distance configured. In my case I had commented out the gear_ratio, but klipper gave a config error. This just updates so that it checks to see if the base stepper has the setting before trying to read it.
> fix: do not require all shared stepper configs (development)

- extras/mmu_machine.py
This fixes PRELOAD functionality with type-b mmu using `gate_homing_endstop: mmu_post_gate`
> fix: use 0 as position for dummy rail

- extras/mmu.py
Update the logic in `_recover_filament_pos` to include a check for the extruder entry endstop. This should help catch cases where a restart left filament past the entry sensor but not yet engaged with the extruder. May also help for devices without a toolhead sensor.
For conditions that would set the position to `FILAMENT_POS_IN_BOWDEN`, now perform a check on the extruder entry endstop and if it is installed and triggered, set the position to `FILAMENT_POS_EXTRUDER_ENTRY` instead of `FILAMENT_POS_IN_BOWDEN`.
Addresses issue #468.
> Check Extruder Entry sensor during filament position recovery

- config/addons/blobifier.cfg
- install.sh
- Purge with a pulsating (and occasionally, retracting) motion. This will prevent laminar flow from occuring and purge the old filament more quicly. (Up to 30% EXTRA filament saved!)
- Changed the blob calculation mode. The blob will now split into equal parts if it is too large (e.g. 2x85mm instead of 150mm + 20mm). This will eliminate/reduce the small blobs scattering over the buildplate.
- Due to the above changes, certain variables have been added and removed:
- new:
- `z_raise`: The total amount the nozzle should be raised during a blob. The value should be somewhere around `iteration_z_raise * max_iterations_per_blob - triangular(iteration) * iteration_z_change`
- `z_raise_exp`: The rate at which the hotend reduces raising speed during a blob. `0.85` seems to be a good starting …
> Blobifier V1.5

- config/addons/README.md
- config/addons/respooler.cfg
- config/addons/respooler_hw.cfg
This updates the respooler addon with the following:
* Reduce code duplication by combining start and stop in one "hidden" macro and then exposing start and stop macros
* Add support for an enable pin that is turned on before starting the motor and turned off after turning off a motor. Note: My setup does not currently have this, so I have not tested this yet.
* Added delayed gcode stuff to automatically stop respoolers after a given amount of time. This is just a precaution to prevent the respooler from running indefinitely. The timeout is configureable, but defaults to 60s.
> feat(addon-respooler): update respooler to combine main logic into a single macro

- install.sh
There's a few updates included here...
- Updates the installer with the following:
- The `prompt_123` now allows numbers greater than 9 and has additional validations and feedback to the user when the value is invalid.
- Add a `prompt_option` function to make menu selection more similar to the bash built-in `select`, while still allowing prompts with less than 10 options to function without having to press enter/return. Similar to the `select` command we have the ability to get the numerical response or the text response (which may be useful if we decide to do some dynamic menus where numerical values may vary)
- For the prompt option/menu things we can define a key for the options and use that as a variable. This removes the need to rely on the option order in the case statement that …
> Update installer (development)

- install.sh
Remove legacy development name to avoid confusion with BoxTurtle
> Update NightOwl name in install.sh

- extras/mmu/mmu.py
Looks like [recent changes](https://github.com/moggieuk/Happy-Hare/commit/7e608f49848be5cc7cf24a301b18c0517e60fa54#diff-47f1fc0c56dacae8e98e2ec82af6b3a5996edf5c9560d6078e4291eb1cf0ddefR3815) to the preload (and eject) code expects this to return the gate number. Without this, we get crashes because gate ends up becoming `None`
> fix: return the selected gate from select_gate

- config/addons/README.md
- config/addons/dc_respooler.cfg
- config/addons/dc_respooler_hw.cfg
- config/base/mmu_parameters.cfg
- config/base/mmu_parameters.cfg.vs
- extras/mmu/mmu.py
This updates the respooler to convert the stepper speed to a value between `0.0` and `1.0` for the respooler speed (if the pin is configured for pwm). There is a step speed exponent value that can be configured as well to give allow scaling the speed exponentially rather than linearly. The default speed configurations favor full speed currently. I will play need to play with these settings a bit to see what might work best as default values (will open a separate PR to adjust them if needed).
It also allows configuring the minimum distance of a move to activate a respooler.
> feat: Update respooler addon to support variable speed and distance filtering

- config/addons/dc_respooler.cfg
- config/addons/dc_respooler_hw.cfg
Added the exponent setting but forgot to actually add it to the calculation.
Also updated default settings
> fix(addon/respooler): actually use the exponent setting

- config/addons/blobifier.cfg
Moved the final retract to the end of the blob, before the z-lift.  Cuts the blob off cleanly, instead of leaving a string on it. This means the blobs separate cleanly in the bucket instead of all tangling together.
My initial testing shows this works better.
I will do some more testing on this and see how it goes, but also released here so others can review it. Overall it makes sense to me to do it this way.
> Move retract to directly after the blob.

- extras/mmu/mmu_selector.py
I noticed when shutting down, this triggers an error because it's not defined.
> fix: add handle_disconnect to virtual selector

- config/base/mmu_parameters.cfg
- extras/mmu.py
Quick fix for sync_multiplier_low parameter name in the config file.
> Fix parameter name (sync_multiplier_low)

- config/addons/dc_espooler.cfg
- config/addons/dc_espooler_hw.cfg
The section `[gcode_macro _MMU_ESPOOLER_VARS]` was defined in both `dc_espooler.cfg` and `dc_espooler_hw.cfg` 
I presume it was some leftover from a refactor. I removed the redundant section in `dc_espooler_hw.cfg`
> Remove duplicate section in espooler

- extras/mmu.py
The PAUSE wrapper in `mmu.py` does not pass along parameters to a user defined macro.
This change uses the pattern in `cmd_RESUME` to pass along parameters when executing the base macro.
> Update `cmd_PAUSE` to pass parameters to the user-defined macro

- components/mmu_server.py
As I was experimenting with Blobifier I noticed that the purge matrix was not changing as the flush multiplier was increased or decreased in Orca slicer as I was trying to validate this Orca slicer PR I've raised here: https://github.com/SoftFever/OrcaSlicer/pull/7508
**For example:**
Multiplier of 1.2
Gcode file:
Multiplier of 0.5
Gcode file:
This results in an incorrect purge matrix being sent to the blobifier for use when purging that does not match the intended action from the user in the UI. Instead the purge matrix is always as if 1.0 multiplier was set in the UI.
This happens because both Orca and Bambu generate a base purge matrix and a separate multiplier and they output both to the gcode for use by Happy Hare etc. To calculate the effective purge volume, these two values need to …
> Parse flush multiplier and adjust flush matrix accordingly to match Orca and Bambu requested purge volumes

- extras/mmu/mmu.py
The code for handling closest_color was missing two calls to .lower() and converted the hex-colors to 0.0-1.0 or 0-255 messing up the actual color matching
> Fixed bugs in closest_color TTG mapping

- extras/mmu/mmu.py
This fixes logic for bowden correction moves.
Example scenario:
1. We move `1500mm` with fast bowden move. Encoder measured `1480mm`. The delta is `20mm` which we need to correct.
2. First correction move will attempt to move `20mm` which will move for example `18mm` according to the encoder, so now our delta is `2mm`. So we are away from `1500mm` destination by only `2mm` and we are at `1498mm`
3.  The delta is updated like this `delta -= d`, so the new delta will be `20mm - 2mm = 18mm`. So when we do the second correction move we will move past the target and end up at `1498mm + 18mm = 1516`
This PR is a simple change to update the original `delta` with the delta from the correction move. Updated logic:
1. We move `1500mm` with fast bowden move. Encoder measured `1480mm`. The delta is …
> Fix bowden load correction moves

- config/base/mmu_parameters.cfg
Trivial fix:
The link to the `MMU_CALIBRATE_TOOLHEAD` documentation had a typo and redirected to the main wiki page.
I have also taken the liberty of adding the anchor to jump to the relevant section.
> fix link to `MMU_CALIBRATE_TOOLHEAD` documentation

- pin_defs
clean up copy paste typo for BTT MMB 1.1 board
- fix for MMB 1.1 board, not properly replaced, causes startup issue. https://github.com/moggieuk/Happy-Hare/issues/578#issuecomment-2577980291
> Update pin_defs for BTT MMB 1.1  board. 

- config/addons/blobifier.cfg
Apply sane limits to prevent users from defining brush and shake accel's that exceed max_accel settings of the printer to minimise potential for missed steps.  Checks added to delayed_gcode blobifier init block
> Warn if user defined accels exceed max_accels defined for the printer.

- install.sh
Hello,
I noticed that many help requests for MMUs are related to not reading documentation. While we can't exactly *make* people read docs, we can at least show them links as frequently as possible. This PR allows two help URLs per MMU to be added to the installer script. Currently, only the 3MS has help URLs, but it should be easy for other MMUs to add help URLs.
Example with the 3MS:
This should hopefully help direct new users to the relevant docs for MMUs and keep MMU help forums focused on things that actually require help, and aren't just a result of not reading the docs.
---
**To add new help URLs**
1. Locate `"$_<YOUR MMU NAME>")` in `install.sh`
2. Add `HELP_URL` below `HAS_SERVO`
3. Optionally, add `HELP_URL_B` below `HELP_URL`
> Add Help URLs to Installer

- extras/mmu/mmu.py
Fixes active spool in spoolman being set after the load sequence is complete. 
The current behaviour triggers the post load macros and then associates the spool from spoolman, meaning that any blobifier purging is not counted against the active filament.
Have moved both the load and unload association from Spoolman for consistency in the code.
Fixes #558
> Fix current spool in spoolman being activated after the load sequence is complete

- extras/mmu/mmu_selector.py
Add missing movequeues_wait that caused the gate parking step to be missed.
> Add missing movequeues_wait to ServoSelector._set_servo_angle()

- components/mmu_server.py
My files were not detecting the colours when pre-processed by Happy-Hare, found out, while looking at the gcode file that the line it was looking for was set as '; extruder_colour = ;;;;;;;' as my extruders are set to have the colour of the filament. This solves the problem by also looking at the filament colour (if the extruder colour is not set)
> Check filament colour in PrusaSlicer as well

- config/base/mmu_macro_vars.cfg
- config/base/mmu_sequence.cfg
add ability to call `variable_user_park_move_macro` on restore position. 
when restoring the from parked postion the same macro is called but passed a RESTORE=1 parameter, along with co-ordinates to restore to `YOUR_MOVE_MACRO RESTORE=1 X=<x_coord> Y=<y_coord> F=<speed>`
```
[gcode_macro _MMU_USER_PARK]
description: always move to X74 first to clear brush then move in the Y direction, followed by the X direction
gcode:
{% if params.RESTORE == 1 %}
G1 X74 F{params.F}
G1 Y{params.Y} F{params.F}
G1 X{params.X} F{params.F}
{% else %}
G1 X74 F{params.F}
G1 Y{params.Y} F{params.F}
G1 X{params.X} F{params.F}
{% endif %}
```
> feat: add ability to call `variable_user_park_move_macro` on restore position

- extras/mmu_sensors.py
This means printing status will fall back to idle_timeout, which reports "Printing" anytime the printer performs any action until the idle timeout occurs. So it really has a different meaning, but I guess octoprint conflicts with using virtual_sdcard (which is what auto loads the print_stats module and updates it's stats).
This was an issue raised [here](https://discord.com/channels/1305204275315474452/1305204561186914376/1337239962827096120)
> fix: set default to None when looking up print_stats module

- extras/mmu/mmu.py
When parsing tool map / purge volumes from the slicer, prefer NxN over from->to list. This fixes invalid purge table when there are only 2 gates.
> Fix calculation of purge volumes from the slicer with only 2 gates

- components/mmu_server.py
Reverts moggieuk/Happy-Hare#631
As I explained in the [discussion on the original PR](https://github.com/moggieuk/Happy-Hare/pull/622#issuecomment-2648306760) after you pointed out that it should take into account the extruder, it looks at the extruder first, as it appears always first in the code file. 
This change makes it so that the filament colours will be checked only if the extruder has no valid colours, which was happening to me as I set my extruders to be the filament colour in PrusaSlicer and they show up as '; extruder_colour = ;;;;;;;'.
As such, I'm reopening this PR.
I want to point out that I should have explained the problem and this solution better in the original PR, sorry.
> Reopen "Check filament colour in PrusaSlicer as well"

- config/base/mmu_cut_tip.cfg
If we need to do a safe travel move, first the cutting axis should be moved and then the other one. I have my cutter on the y axis and moving x first would cause the lever to crash into the pin.
> fix: make safe travel move dependent on cutting axis

- extras/mmu/mmu_selector.py
Fixes issue reported [here](https://discord.com/channels/1305204275315474452/1307001795096084500/1340910903603888170).
[klippy.log](https://github.com/user-attachments/files/18821198/klippy.39.log)
First exception during startup:
```
Unhandled exception during run
Traceback (most recent call last):
File "/home/pi/klipper/klippy/klippy.py", line 176, in run
self.reactor.run()
File "/home/pi/klipper/klippy/reactor.py", line 292, in run
g_next.switch()
File "/home/pi/klipper/klippy/reactor.py", line 340, in _dispatch_loop
timeout = self._check_timers(eventtime, busy)
File "/home/pi/klipper/klippy/reactor.py", line 158, in _check_timers
t.waketime = waketime = t.callback(eventtime)
File "/home/pi/klipper/klippy/webhooks.py", line 496, in _do_query
res = query[obj_name] = …
```
> fix: return status for rotary selector

- install.sh
The previous default of 70 was too short and made it so you had to be really fast once you get the filament through the pre-load sensor. Setting this to something longer allows it to essentially try preloading longer so you have more time to get that filament pushed down to the gear
> fix(boxturtle): Increase default gate_preload_homing_max to 200

- config/addons/blobifier.cfg
Added a variable (fan_name) to allow restoring fan speed after using Blobifier if one is using a fan definition other than [fan] for a part fan.
For example, I am using the [auxiliary fan functionality](https://github.com/SoftFever/OrcaSlicer/wiki/Auxiliary-fan) in OrcaSlicer which has a different configuration in order to use properly in which the part fan is controlled using a [fan_generic] definition and an override of the M106 command. Therefore, using printer.fan.speed to get the current fan speed and save it as `backup_fan_speed` will result in the "true" part fan being set to 0.
The implementation is compatible with either configuration of part fan with the variable providing a default example which is the suggested configuration provided by the OrcaSlicer wiki.
> Accommodate fans other than [fan] in Blobifier

- extras/mmu/mmu.py
Previously if the color had an alpha channel (e.g. DFB1C0FF), then in `_color_to_rgb_tuple` it would not parse the color and just return all black. In my latest print I had the following colors (first 3 from spoolman via alpha mainsail ui, last one was manual)
```
color_list = ['111111FF', 'CFCCD6FF', 'DFB1C0FF', '042f56']
```
Then doing a test with, the following, both got mapped to `042f56` since that one is closest to black.
```
print(_find_closest_color('042F56', color_list))
print(_find_closest_color('CFCCD6', color_list))
```
> fix: ensure rgb hex is no more than 6 characters

- extras/mmu/mmu.py
- extras/mmu/mmu_test.py
- extras/mmu_sensors.py
Hi @moggieuk ,
It's me at it again =) I'm currently experiencing issues regarding the sync_feedback feature and whilst reading through the implementation i noticed some things.
- I might have stumbled upon some bugs see commit 944bbbdc2e67797799005c1ae48e0a6e1a8d40d8. Is this intended ? It seemed weird you would reset the direction to state but it might not have consequences.
- Another strange thing here see commit 0b9695eb236fd27cef46096541ca3d5463661fe1. I feels like the `multiplier = 1` should more depend on the state rather than the direction ?
- In the sensor description, i might not have understood this correctly but it seems we should check for filament_present additionally to enabled ? (see commit 4d92abd8de5790bf3ddf8da1f027178336216b08)
Additionally I'm experiencing issues on my …
> Sync mechanism fixing and/or enhancing 

- config/addons/blobifier.cfg
Fixes https://github.com/moggieuk/Happy-Hare/issues/655. Correct variable used to display current value for z_raise_exp (was incorrectly using z_raise). Ready to merge.
> Blobifier: Display correct variable value for z_raise_exp validation check

- config/base/mmu_macro_vars.cfg
This resolves klipper invalid syntax error reported [here](https://discord.com/channels/1305204275315474452/1329355247478505472/1362672240856137812)
> fix: Add whitespace between end quote and comment marker

- config/base/mmu_form_tip.cfg
- config/base/mmu_macro_vars.cfg
Added variable_fan_name for using [auxiliary fan](https://github.com/SoftFever/OrcaSlicer/wiki/Auxiliary-fan) in Orcaslicer, which redefines part cooling fan as a generic fan, during tip forming workflow.
See #649 for a similar use case.
#669
> Tip forming part cooling fan assist for generic fan

- extras/mmu/mmu.py
Slicers generally send the color information as RGB, but Mainsail and Fluidd will set color information as RGBA, at least when using spoolman.
This leads to matching filaments not being chosen when using the exact color strategy.
This change pads both halves of the comparison with an FF alpha value as necessary, enabling colors without alpha information to match fully opaque colors.
@ammmze suggested another elif to ensure the non-color-values in other exact comparison strategies are not padded. I chose to check for the `AUTOMAP_COLOR` strategy to match the existing condition.
Draft while I wait for an opportunity to test.
> automapping by color: handle alpha values

- extras/mmu/mmu.py
Fix extruder_name for multiextruders printers.
This line was not using self.extruder_name and it was hardcoded to "extruder"
> Fix extruder_name for multiextruders printers.

- config/addons/blobifier.cfg
- extras/mmu_machine.py
This PR introduces a new configurable parameter to the BLOBIFIER macro system, allowing users to define a custom X-axis position (shaker_pos_x) for the BLOBIFIER_SHAKE_BUCKET macro. This makes the macro compatible with setups where the shaker tray is positioned at a negative or non-standard X location.
> Add ability to specify X pos for shaker in Blobifier

- extras/mmu/mmu.py
Otherwise the sensors are in a JSON format and then the log formatter thinks the `{ ... }` are placeholders of some sort and would lead to the following error:
```
File "/home/pi/klipper/klippy/extras/mmu/mmu.py", line 4565, in _unload_bowden
self.log_warning("Warning: Possible sensor malfunction - a sensor indicated filament not present before unloading bowden: %s\nWill attempt to continue..." % sensors)
File "/home/pi/klipper/klippy/extras/mmu/mmu.py", line 1803, in log_warning
self.log_always("{2}%s{0}" % msg, color=True)
File "/home/pi/klipper/klippy/extras/mmu/mmu.py", line 1806, in log_always
html_msg, msg = self._color_message(msg) if color else (msg, msg)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/pi/klipper/klippy/extras/mmu/mmu.py", line 1785, in _color_message
html_msg = …
```
> fix: Convert sensors to a text format before passing it to the log

- config/base/mmu_parameters.cfg
Spelling error in blobifier macro name in comment. 
If copied and pasted will not call the macro.
> Spelling error for BLOBIFIER macro in comment in mmu_parameters.cfg

- .gitignore
- extras/mmu/mmu.py
Restoring previous behaviour where after a run out and endless spool triggering, the purge macros (blobifier) where invoked. In previous releases that was done automatically as the blobifier was tied to the post load macro user hook. 
This is particularly helpful to avoid blobs on the print if the toolhead dimensions and ooze reduction are not spot on (which is not as critical when a purge macro is used) and to ensure consistent nozzle pressure when the new filament is loaded and any air pockets in the nozzle caused by filament retraction, loading and inevitable ooze during the process, are purged out.
Tested with an endless spool operation in latest HH with success.
(also adding .DS_Store files automatically generated by MacOS to the git ignore list to prevent them polluting the repo).
> Enable purging (blobifier) when run out occurs

- install.sh
Some busybox grep versions only accept short form parameters.
```
grep: unrecognized option '--quiet'
BusyBox v1.31.1 (2024-03-15 11:13:52 CST) multi-call binary.
```
Should have no impact on GNU grep as it supports both forms.
> Replace long form grep parameters with short form.

- extras/mmu/mmu.py
Previous behaviour would erroneously set the last tool to be the current tool if a tool change failure happened and the retry_tool_change_on_error was set to 1. This would cause downstream components (blobifier) to purge the wrong filament quantity as to the blobifier it appeared as if no tool change happened.
> Remember correctly the last fully loaded tool if option to retry_tool_change_on_error is set
