moonraker_update.txt
Add primary_branch to the config section.
=> fix: fix Moonraker update section

extras/mmu.py
**Issue:**
If the MMU is disabled with `MMU ENABLE=0` when a print is paused, certain timer-based events (like the heater timeout) don't get reset, causing the print to fail down the line. This can happen when a print is meant to bypass the MMU entirely but you forget to disable until the MMU pauses for a suspected print fault
**Fix Description:**
Simply adds a teardown method when disabling the MMU that resets certain timers/state to their default values. Also slightly refactors the MMU enable/disable logic by extracting them into their own methods for use outside of `cmd_MMU` 
**GitHub Issues Resolved:**
None
=> Added teardown method for MMU state

extras/mmu.py
fix for issue https://github.com/moggieuk/Happy-Hare/issues/33#issue-1884725929
=> Fix time format for mmu.lof

README.md, config/base/mmu_parameters.cfg, extras/mmu.py
This introduces a new config option called "gate_spool_id:". 
When set, these IDs represent the SpoolIDs in SpoolMan and are used to activate the spool then the tool is loaded
=> SpoolMan integration 

components/mmu_server.py
Fixes way spools are fetched from spoolman, former filament.id was looking up filaments instead of spools - according to spoolman api fetching them one by one seems to be only way
=> Fix fetching spoolman spool data

extras/mmu.py
Gate_unload_buffer appears already subtracted in unload_bowden -- this fix my broken bowden calibration
=> remove double subtraction of gate_unload_buffer

components/mmu_server.py
BEWARE! I have not tested this with slicers, because I don't have SS set up. However, testing in a simulated environment seemed to work.
=> Fixed color pre-processing mismatch in SS. empty colors were picked up

install.sh
Changed `Unappy` to `Unhappy`.
=> Fixed typo

doc/configuration.md
Updated the CW2 dimensions for the Rapido/Rapido2 hotend setup with verified dimensions
=> Update CW2/Rapido data in configuration.md

README.md
=> Fix first wiki link url in README.md

config/addons/blobifier.cfg
Adds checks pre-print to ensure safe descend is possible without hitting other prints.
=> Blobifier safe descend update

extras/mmu.py
fixed this issue
https://github.com/moggieuk/Happy-Hare/issues/397
fixed a bug that sometimes tension sensor is never read and the tension state is never updated.
filament sync tension is never corrected with two sensors set up in some cases
**Steps to reproduce:**
1 printer has expand and compress sensors setup, two, not one. ( expand sensor for too little filament, compress sensor for too many filament ) 2 manually put more filament in tube to make the compressed sensor triggered. 3 manually set the mmu_hardware.cfg file rotation_distance to a obvious smaller value , ie 20. ( so ERCF shall push more filament than it should)
Restart raspberry PI controller computer or klipper ( sudo service klipper restart ), things are correct, (this explains why sometimes it works sometimes it doesn't. …
=> read tension sensor state when sync feedback is enabled

components/mmu_server.py, config/base/mmu_cut_tip.cfg, config/base/mmu_macro_vars.cfg
Adds a parameter named cutting_axis in mmu_macro_vars.cfg. Renames several to be axis-independent. Update g code to respect the new cutting_axis variable.
=> Support for Y axis cutting motion

extras/mmu/mmu.py
The main thing I'd like to introduce here is the ability to perform the auto bowden calibration when you have an extruder entry sensor. 
There's a handful of additional changes included which can be seen as individual commits.
=> Auto bowden calibration w/o encoder

config/addons/README.md, config/addons/dc_espooler.cfg, config/addons/dc_espooler_hw.cfg, config/base/mmu_parameters.cfg, config/base/mmu_parameters.cfg.vs, extras/mmu_sensors.py
Also includes the one change to the runout sensor to use `print_stats` instead of `idle_timeout` to determine if we are "printing".
=> refactor: Finalize respooler > eSpooler rename

config/base/mmu_sequence.cfg
Change variable name "lift_speed" to "park_lift_speed".
=> Fix mmu_sequence.cfg wrong variable names

extras/mmu_machine.py
added set_direction function to mum_rail
need for gear direction for 3DChameleon
=> expose set_dir_inverted in rail

README.md, config/addons/blobifier.cfg, config/addons/dc_espooler.cfg, config/addons/mmu_erec_cutter.cfg, config/base/mmu_hardware.cfg, config/base/mmu_macro_vars.cfg, config/base/mmu_parameters.cfg, config/base/mmu_sequence.cfg, config/base/mmu_software.cfg
I've given the entire repo a once-over with the dictionary.
There is only two changes in executed code, both in `action_respond_*`s. All other changes are in comments only.
=> various spelling fixes

config/addons/blobifier.cfg, config/base/mmu_macro_vars.cfg
Moved the dwell_time variable to be close to the blobifier servo secrtion; Fixed a typo I saw
=> Move servo variables to the same blobifier section

components/mmu_server.py
Reverts moggieuk/Happy-Hare#622
Waiting for some more testing validation...
=> Revert "Check filament colour in PrusaSlicer as well"

components/mmu_server.py
added the new -c argument and edited the main function calls to work with the new klipper_estimator feature provided by moonraker
should fix #641
=> fix mmu_server.py to work with recent update to moonrakers metdata.py

extras/mmu/mmu_selector.py, extras/mmu_machine.py
See discussion in Discord starting [here](https://discord.com/channels/1305204275315474452/1344365129210527785/1348306078126837820)
=> feat(pico): implement filament release for pico

extras/mmu_machine.py
In klipper v0.13.0-79 (from Klipper3d/klipper#6815) the printer rail code was refactored and requires some refactoring on our side
I did very basic testing on both klipper v0.13.0-79 and v0.13.0-78 (`git reset --hard 1cc63980747b80516f8fc4f022eedf18ae739086`) and verified klipper could start and then used `MMU_CHECK_GATES` to ensure it could move each of the mmu gear steppers in my Box Turtle.
=> fix: support klipper v0.13.0-79

config/base/mmu.cfg
I have corrected pintout on espooler 2 to avoid getting errors.
=> Wrong pinout on ESPOOLER_FWD_2 mmu.cfg
